name = "verified-compiler-notes"
defaultTargets = [
  "VerifiedCompilerNotes",
  "verified-compiler-notes",
  "verified-compiler-notes-pdf",
]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "main"

[[lean_lib]]
name = "VerifiedCompilerNotes"

[[lean_exe]]
name = "verified-compiler-notes"
root = "VerifiedCompilerNotesMain"

[[lean_exe]]
name = "verified-compiler-notes-pdf"
root = "VerifiedCompilerNotesPdfMain"
